//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentChallenge.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevelopmentChallenge.Data.Resources.Idioma", typeof(Idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area .
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Círculo.
        /// </summary>
        internal static string Círculo {
            get {
                return ResourceManager.GetString("Círculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Círculos.
        /// </summary>
        internal static string Círculos {
            get {
                return ResourceManager.GetString("Círculos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuadrado.
        /// </summary>
        internal static string Cuadrado {
            get {
                return ResourceManager.GetString("Cuadrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuadrados.
        /// </summary>
        internal static string Cuadrados {
            get {
                return ResourceManager.GetString("Cuadrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a formas.
        /// </summary>
        internal static string formas {
            get {
                return ResourceManager.GetString("formas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h1&gt;Lista vacía de formas!&lt;/h1&gt;.
        /// </summary>
        internal static string ListaVacia {
            get {
                return ResourceManager.GetString("ListaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  | Area .
        /// </summary>
        internal static string ObtenerLineaArea {
            get {
                return ResourceManager.GetString("ObtenerLineaArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  | Perimetro .
        /// </summary>
        internal static string ObtenerLineaPerimetro {
            get {
                return ResourceManager.GetString("ObtenerLineaPerimetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perimetro .
        /// </summary>
        internal static string Perimetro {
            get {
                return ResourceManager.GetString("Perimetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h1&gt;Reporte de Formas&lt;/h1&gt;.
        /// </summary>
        internal static string PorLoMenosUna {
            get {
                return ResourceManager.GetString("PorLoMenosUna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trapecio Rectángulo.
        /// </summary>
        internal static string Trapecio_Rectángulo {
            get {
                return ResourceManager.GetString("Trapecio Rectángulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trapecios Rentángulos.
        /// </summary>
        internal static string Trapecios_Rentángulos {
            get {
                return ResourceManager.GetString("Trapecios Rentángulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triángulo.
        /// </summary>
        internal static string Triángulo {
            get {
                return ResourceManager.GetString("Triángulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triángulos.
        /// </summary>
        internal static string Triángulos {
            get {
                return ResourceManager.GetString("Triángulos", resourceCulture);
            }
        }
    }
}
